### ISSUE TITLE
Backend platform selection

### ISSUE THREAD

**Issue by gmichael225** [matt-dale/designdb#3]
Which way d'you want to go?

NodeJS + Express?
PHP + Slim / Cake?
Django again?
Ruby on Rails?

Most of my experience is with the Node/PHP, but happy to work with others.

**Comment by matt-dale** [comment]
I would definitely prefer Django and/or Flask due to my familiarity with it and potential reusable code. The features that I believe to be important that come with Django are:
- ORM
- Built-in admin
- Extendable user/group/authentication system
- "Jinja2-like" templating system

Flask is purportedly "lighter weight" and the current codebase definitely uses Views coded similarly to Flask's conventions.  

Generally the system is built with the typical synchronous request>response flow, but I can see a system that we will need a more asynchronous system, which Node can help with(from what I can tell). 

Do you see any reason NOT to use Django? Looking at the Wiki, specifically the visual designer that I'd like to build, my plan was to use Django as an API to the database.

**Comment by gmichael225** [comment]
No reason not to use it that I can see!

Re: architecture, are you planning for Django to handle the views, etc, or to have a single-page application on the frontend and have Django just deliver an API? I'm a fan of the latter approach myself, partly because doing everything with XHR gives a considerably better user experience (rather than constant page reloads).

**Comment by matt-dale** [comment]
Yes, I plan on using the latter approach.
The Django vocabulary is a little different checkout this page: https://docs.djangoproject.com/en/1.9/faq/general/#django-appears-to-be-a-mvc-framework-but-you-call-the-controller-the-view-and-the-view-the-template-how-come-you-don-t-use-the-standard-names

Django has built in URLs for manipulating the database Models, but I find it easier to read and more customizable to create my own

**Comment by matt-dale** [comment]
Closing, since I just started the Django project.  We may revisit this in the future.
